CREATE COLUMN TABLE "I075903"."MY_SEGMENGS_TILES_14" ("SEGMENT_ID" BIGINT CS_FIXED,
     "Z" INTEGER CS_INT,
     "X" INTEGER CS_INT,
     "Y" INTEGER CS_INT) UNLOAD PRIORITY 0 AUTO MERGE ;


CREATE COLUMN TABLE "I075903"."TILE_IMAGE" ("Z" INTEGER CS_INT,
     "X" INTEGER CS_INT,
     "Y" INTEGER CS_INT,
     "TIMESTAMP" LONGDATE CS_LONGDATE,
     "CONTENT" CLOB MEMORY THRESHOLD 1000,
     PRIMARY KEY ("Z",
     "X",
     "Y")) UNLOAD PRIORITY 5 AUTO MERGE ;
